name: nsc2026
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - aws-c-auth=0.9.3=h1ddaa69_0
  - aws-c-cal=0.9.13=h6ee9776_1
  - aws-c-common=0.12.6=hc919400_0
  - aws-c-compression=0.3.1=h16f91aa_9
  - aws-c-event-stream=0.5.7=h9ae9c55_1
  - aws-c-http=0.10.7=h5928ca5_5
  - aws-c-io=0.23.3=hbe03c90_5
  - aws-c-mqtt=0.13.3=haf5c5c8_11
  - aws-c-s3=0.11.3=h8da9771_1
  - aws-c-sdkutils=0.2.4=h16f91aa_4
  - aws-checksums=0.2.7=h16f91aa_5
  - aws-crt-cpp=0.35.4=h74951b9_0
  - aws-sdk-cpp=1.11.606=h4e1b0f7_10
  - azure-core-cpp=1.16.1=h88fedcc_0
  - azure-identity-cpp=1.13.2=h853621b_1
  - azure-storage-blobs-cpp=12.16.0=h6507aac_0
  - azure-storage-common-cpp=12.12.0=ha416c23_0
  - azure-storage-files-datalake-cpp=12.14.0=hcfc4f22_0
  - backports.zstd=1.3.0=py311hee243d0_0
  - bokeh=3.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=h7d5ae5b_1
  - brotli-bin=1.2.0=hc919400_1
  - brotli-python=1.2.0=py311hdc60ec4_1
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - click=8.3.1=pyh8f84b5b_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py311h7d85929_4
  - cycler=0.12.1=pyhcf101f3_2
  - cytoolz=1.1.0=py311h9408147_1
  - dask=2026.1.2=pyhcf101f3_0
  - dask-core=2026.1.2=pyhcf101f3_0
  - distributed=2026.1.2=pyhcf101f3_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - fonttools=4.61.1=py311ha9b3269_0
  - freetype=2.14.1=hce30654_0
  - fsspec=2026.1.0=pyhd8ed1ab_0
  - gflags=2.2.2=hf9b8971_1005
  - glog=0.7.1=heb240a5_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h38cb7af_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhcf101f3_1
  - kiwisolver=1.4.9=py311h26d6576_2
  - krb5=1.21.3=h237132a_0
  - lcms2=2.18=hdfa7624_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libarrow=23.0.0=h4365f54_1_cpu
  - libarrow-acero=23.0.0=h6de58dd_1_cpu
  - libarrow-compute=23.0.0=h45df96a_1_cpu
  - libarrow-dataset=23.0.0=h6de58dd_1_cpu
  - libarrow-substrait=23.0.0=hb5627e6_1_cpu
  - libblas=3.11.0=5_h51639a9_openblas
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.18.0=he38603e_0
  - libcxx=21.1.8=h55c6f16_2
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=hcf2aa1b_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_17
  - libgfortran=15.2.0=h07b0088_17
  - libgfortran5=15.2.0=hdae7583_17
  - libgoogle-cloud=2.39.0=head0a95_0
  - libgoogle-cloud-storage=2.39.0=hfa3a374_0
  - libgrpc=1.73.1=h3063b79_1
  - libiconv=1.18=h23cfdf5_2
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=5_hd9741b5_openblas
  - liblzma=5.8.2=h8088a28_0
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_4
  - libopentelemetry-cpp=1.21.0=he15edb5_1
  - libopentelemetry-cpp-headers=1.21.0=hce30654_1
  - libparquet=23.0.0=hcc2992d_1_cpu
  - libpng=1.6.54=h132b30e_0
  - libprotobuf=6.31.1=h98f38fd_4
  - libre2-11=2025.11.05=h91c62da_0
  - libsqlite=3.51.2=h1ae2325_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.1=h4030677_1
  - libutf8proc=2.11.3=h2431656_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h8d039ee_1
  - libxml2-16=2.15.1=h5ef1a60_1
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.8=h4a912ad_0
  - llvmlite=0.46.0=py311h27de090_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.5=py311h3f5a5ee_1
  - lz4-c=1.10.0=h286801f_1
  - markupsafe=3.0.3=py311ha9b3269_0
  - matplotlib=3.10.8=py311ha1ab1f8_0
  - matplotlib-base=3.10.8=py311h29553df_0
  - msgpack-python=1.1.2=py311h5a5e7c7_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.16.0=pyhcf101f3_0
  - ncurses=6.5=h5e97a16_3
  - nlohmann_json=3.12.0=h784d473_1
  - numba=0.63.1=py311had9367a_0
  - numpy=2.3.5=py311had1e860_1
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.1=hd24854e_1
  - orc=2.2.2=hac85105_0
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.0=py311h4a068b9_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pillow=12.1.0=py311hd37aea2_0
  - pip=26.0.1=pyh8b19718_0
  - pluggy=1.6.0=pyhf9edf01_1
  - prometheus-cpp=1.3.0=h0967b3e_0
  - psutil=7.2.2=py311he363849_0
  - pthread-stubs=0.4=hd74edd7_1002
  - pyarrow=23.0.0=py311ha1ab1f8_0
  - pyarrow-core=23.0.0=py311h311f44d_0_cpu
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=9.0.2=pyhcf101f3_0
  - python=3.11.14=h18782d2_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=8_cp311
  - pyyaml=6.0.3=py311hc290fe0_1
  - qhull=2020.2=h420ef59_5
  - re2=2025.11.05=h64b956e_0
  - readline=8.3=h46df422_0
  - scipy=1.17.0=py311he9931d0_1
  - setuptools=80.10.2=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=hada39a4_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - tblib=3.2.2=pyhcf101f3_0
  - tk=8.6.13=h010d191_3
  - tomli=2.4.0=pyhcf101f3_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.4=py311h9408147_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=17.0.0=py311h9408147_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - yaml=0.2.5=h925e9cb_3
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.3.3=hed4e4f5_1
  - zstd=1.5.7=hbf9d68e_6

prefix: "/Users/paolapolanco/miniforge3/envs/nsc2026"
